#!/usr/bin/perl
# test classification with bayes

use strict;
use warnings;

use lib 'lib';

use SentimentAnalysis::Bayes;

my $bayes = SentimentAnalysis::Bayes->new(filename => 'databayes');

my $newcount = 0;
my $oldcount = 0;

while (<>) {
    chomp;

    my ($class, $line) = split /\t/, $_, 2;

    my @words = split /\s+/, $_;

    my %count;
    foreach my $word (@words) {
        $word = lc $word;
        $word =~ s/^[^a-z]*//;
        $word =~ s/[^a-z]*$//;

        next if $word eq '';

        $count{$word}++;
    }

    $newcount++ if $class eq $bayes->classify(\%count);
    $oldcount++ if $class eq $bayes->_old_classify(\%count);
}

print "new\t$newcount\n";
print "old\t$oldcount\n";
