#!/usr/bin/perl
# train sentiment analysis (really, train a generic naive bayes classifier)
# James Stanley 2013

use strict;
use warnings;

use lib 'lib';

use SentimentAnalysis::Bayes;

my $bayes = SentimentAnalysis::Bayes->new( filename => 'databayes' );

while (<>) {
    chomp;

    my ($class, $line) = split /\t/, $_, 2;

    next if $class eq 'neutral';

    my @words = split /\s+/, $line;

    foreach my $word (@words) {
        $word = lc $word;
        $word =~ s/^[^a-z]*//;
        $word =~ s/[^a-z]*$//;
        $bayes->add($word => $class);
    }
}

$bayes->save;
